"""add_user_api_keys

Revision ID: 5ec37d6fc5cc
Revises: 29e2bdeb4d73
Create Date: 2026-02-19 19:29:00.668973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec37d6fc5cc'
down_revision: Union[str, Sequence[str], None] = '29e2bdeb4d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_openai_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('encrypted_google_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_google_key')
    op.drop_column('users', 'encrypted_openai_key')
    # ### end Alembic commands ###
