"""drop consensus_score

Revision ID: 65a85c1fcc64
Revises: 5ec37d6fc5cc
Create Date: 2026-02-20 13:36:09.629133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a85c1fcc64'
down_revision: Union[str, Sequence[str], None] = '5ec37d6fc5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debates', 'consensus_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('consensus_score', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
